version: '3.0'
services:
  darkwire.io:
    environment:
      - NODE_OPTIONS="--max-old-space-size=512"
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - db
    ports:
      - 3001:3001
networks:
  db:
